name: 'Run Friesian Python Pip Py37 Spark3'
description: 'Run Friesian Python Pip Py37 Spark3'
runs:
  using: "composite"
  steps:
    - name: Run Test
      shell: bash
      run: |
        cd scala
        mvn clean package -DskipTests -P spark_3.x -Dspark.version=3.1.3 -U
        cd -
       
        #wget https://archive.apache.org/dist/spark/spark-3.1.3/spark-3.1.3-bin-hadoop2.7.tgz -O ${{ github.workspace }}/spark-3.1.3-bin-hadoop2.7.tgz
        #tar -xf spark-3.1.3-bin-hadoop2.7.tgz -C ${{ github.workspace }}/
        #export SPARK_HOME=${{ github.workspace }}/spark-3.1.3-bin-hadoop2.7
      
        source activate py37
        export SPARK_LOCAL_HOSTNAME=localhost
        pip install pyspark==3.1.3 
        chmod a+x python/dev/release_default_linux_spark313.sh
        ./python/dev/release_default_linux_spark313.sh default false false
        
        # install dllib
        pip install -i https://pypi.org/simple python/dllib/src/dist/bigdl_dllib_spark3-*-py3-none-manylinux1_x86_64.whl
        # install orca
        pip install -i https://pypi.org/simple python/orca/src/dist/bigdl_orca_spark3-*-py3-none-manylinux1_x86_64.whl
        # install friesian
        pip install -i https://pypi.org/simple python/friesian/src/dist/bigdl_friesian_spark3-*-py3-none-manylinux1_x86_64.whl
        python -m pytest -v python/friesian/test/bigdl/friesian/feature/
        source deactivate
      env:
        BIGDL_ROOT: ${{ github.workspace }}
        ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
