apiVersion: v1
kind: Pod
spec:
  containers:
  - name: spark-driver
    securityContext:
      privileged: true
    env:
      - name: ATTESTATION
        value: false
      - name: ATTESTATION_URL
        value: your_attestation_url
      #- name: PCCS_URL
      #  value: your_pccs_url
      #- name: APP_ID
      #  valueFrom:
      #    secretKeyRef:
      #      name: kms-secret
      #      key: app_id
      #- name: API_KEY
      #  valueFrom:
      #    secretKeyRef:
      #      name: kms-secret
      #      key: app_key
      #- name: ATTESTATION_POLICYID
      #  valueFrom:
      #    secretKeyRef:
      #      name: kms-secret
      #      key: policy_id
    volumeMounts:
      - name: device-plugin
        mountPath: /var/lib/kubelet/device-plugins
      - name: aesm-socket
        mountPath: /var/run/aesmd/aesm.socket
      - name: nfs-storage
        mountPath: /ppml/trusted-big-data-ml/work/data
      - name: secure-keys
        mountPath: /ppml/trusted-big-data-ml/work/keys
      - name: kubeconfig
        mountPath: /root/.kube/config
     #resources:
      #requests:
        #cpu: 16
        #memory: 128Gi
        #sgx.intel.com/epc: 133258905600
        #sgx.intel.com/enclave: 10
        #sgx.intel.com/provision: 10
      #limits:
        #cpu: 16
        #memory: 128Gi
        #sgx.intel.com/epc: 133258905600
        #sgx.intel.com/enclave: 10
        #sgx.intel.com/provision: 10
  volumes:
    - name: device-plugin
      hostPath:
        path: /var/lib/kubelet/device-plugins
    - name: aesm-socket
      hostPath:
        path: /var/run/aesmd/aesm.socket
    - name: secure-keys
      secret:
        secretName: ssl-keys
    - name: nfs-storage
      persistentVolumeClaim:
        claimName: nfsvolumeclaim
    - name: kubeconfig
      secret:
        secretName: kubeconfig-secret
