name: Chronos PRVN Python Spark2.4 py37 ray

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the main branch
  pull_request:
    branches: [ main ]
    paths:
      - 'python/chronos/src/**'
      - 'python/chronos/test/**'
      - 'python/nano/src/**'
      - 'python/orca/src/bigdl/orca/automl/**'
      - 'python/orca/src/bigdl/orca/data/**'
      - '.github/workflows/chronos-prvn-python-spark-2.4-py37-ray.yml'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  chronos-PRVN-ray:
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7.10"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up Maven
        uses: ./.github/actions/maven-setup-action

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade setuptools==58.0.4
          python -m pip install --upgrade wheel

      - name: Run Chronos python test
        shell: bash
        run: |
          if conda info --env | grep "chronos-prvn-env-1"; then
            source deactivate
            conda remove -n chronos-prvn-env-1 -y --all
          fi
          conda create -n chronos-prvn-env-1 -y python==3.7.10 setuptools==58.0.4
          source activate chronos-prvn-env-1
          pip install boto3==1.24.96
          pip install pytest==5.4.1
          pip install prophet==1.1
          pip install pmdarima==1.8.4
          pip install neural-compressor==1.11
          pip install tsfresh==0.17.0
          pip install ray==1.9.2 ray[tune]==1.9.2 ray[default]==1.9.2
          pip install pyarrow==6.0.1
          pip install ConfigSpace==0.5.0
          pip install optuna==2.10.1
          pip install onnx==1.11.0
          pip install onnxruntime==1.11.1
          pip install openvino-dev==2022.2.0
          pip install onnxsim==0.4.8
          pip install scipy==1.5.4
          pip install cloudpickle
          pip install matplotlib
          apt-get update
          apt-get install patchelf
          pip uninstall -y bigdl-friesian bigdl-friesian-spark3 bigdl-dllib bigdl-dllib-spark3 bigdl-orca pyspark bigdl-orca-spark3 bigdl-chronos bigdl-chronos-spark3 bigdl-nano bigdl-friesian bigdl-friesian-spark3
          #sed -i "s/'bigdl-core=='+VERSION/'bigdl-core==2.1.0b20220811'/g" python/dllib/src/setup.py
          bash python/dev/release_default_linux_spark246.sh default false false
          bash python/nano/dev/build_and_install.sh linux default false pytorch --force-reinstall --no-deps -U
          whl_name=`ls python/nano/dist/`
          pip install python/nano/dist/${whl_name}[tensorflow,pytorch]
          pip install python/dllib/src/dist/bigdl_dllib-*-py3-none-manylinux1_x86_64.whl
          pip install python/orca/src/dist/bigdl_orca-*-py3-none-manylinux1_x86_64.whl
          pip install python/chronos/src/dist/bigdl_chronos-*-py3-none-manylinux1_x86_64.whl
          export SPARK_LOCAL_HOSTNAME=localhost
          export KERAS_BACKEND=tensorflow
          bash python/chronos/dev/test/run-pytests.sh
          source deactivate
          conda remove -n chronos-prvn-env-1 -y --all
        env:
          BIGDL_ROOT: ${{ github.workspace }}
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
