name: Performance Regression Test

on:
  schedule:
    - cron: '0 16 * * *'
  issue_comment:
    types: [created]
  pull_request:
    branches: [ main ]
    paths:
      - '.github/workflows/performance-regression-test.yml'

jobs:
  performace-regression-test:
    runs-on: [Rohan, ubuntu-20.04-lts]
    if: github.event.pull_request || github.event.schedule || github.event.issue.pull_request && github.event.comment.body=='APRT'
    steps:
      # trigged by opening a PR which modifies this file or scheduling or commenting 'APRT' in a closed PR
      - name: checkout (open pr or schedule or closed pr comments)
        if: github.event.pull_request || github.event.schedule || github.event.issue.pull_request.merged_at
        uses: actions/checkout@v3

      # trigged by commenting 'APRT' in an opening PR
      - name: checkout (opening pr comments)
        if: github.event.issue.pull_request && !github.event.issue.pull_request.merged_at
        uses: actions/checkout@v3
        with:
          ref: ${{ format('refs/pull/{0}/merge', github.event.issue.number) }}

      - name: Set up Python 
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install wheel
          pip install twine
          pip install psycopg2-binary
          pip install requests

      - name: Run benchmark
        run: |
          python python/benchmark/run.py nano resnet_inference
          python python/benchmark/run.py nano resnet50
        env:
          USER: ${{ github.actor }}
          PR_URL: ${{ github.event.comment.issue_url }}/comments
          COMMENT_URL: ${{ github.event.comment.html_url }}
          JOB_URL: https://github.com/intel-analytics/BigDL/actions/runs/${{ github.run_id }}
          ANALYTICS_ZOO_ROOT: ${{ github.workspace }}
          IS_PR: ${{ github.event.pull_request != null || github.event.issue.pull_request != null }}
          IS_COMMENTS: ${{ github.event.issue.pull_request != null }}
