name: PR Validation

# Cancel previous runs in the PR when you push new commits
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

on:
      
  pull_request:
    branches: [ main ]
    paths:
      - 'scala/friesian/**'
      - '.github/actions/friesian-scala-ut-action/action.yml'
      - 'scala/dllib/**'
      - '.github/actions/dllib-scala-ut-action/action.yml'
      - 'scala/ppml/**'
      - '.github/actions/ppml-scala-ut-action/action.yml'
      - 'python/orca/**'
      - '.github/actions/orca-ray-ctx-example-action/action.yml'
      - '.github/actions/orca/**'
      - 'python/ppml/**'
      - '.github/actions/ppml/**'
      - 'python/friesian/**'
      - '.github/actions/friesian/**'
      - '.github/workflows/PR_validation.yml'
      - '.github/actions/python-requirements/**'


permissions:
  contents: read
  packages: write

jobs:
  changes:
    name: Paths filter
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]
    outputs:
      friesian: ${{ steps.filter.outputs.friesian }}
      dllib: ${{ steps.filter.outputs.dllib }}
      orca: ${{ steps.filter.outputs.orca }}
      ppml: ${{ steps.filter.outputs.ppml }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            friesian:
              - 'scala/friesian/**'
              - '.github/actions/friesian-scala-ut-action/action.yml'
              - 'python/friesian/**'
              - '.github/actions/friesian/**'
              - '.github/actions/python-requirements/**'
            dllib:
              - 'scala/dllib/**'
              - '.github/actions/dllib-scala-ut-action/action.yml'
              - '.github/actions/python-requirements/**'
            ppml:
              - 'scala/ppml/**'
              - '.github/actions/ppml-scala-ut-action/action.yml'
              - 'python/ppml/**'
              - '.github/actions/ppml/**'
              - '.github/actions/python-requirements/**'
            orca:
              - 'python/orca/**'
              - '.github/actions/orca-ray-ctx-example-action/action.yml'
              - '.github/actions/orca/**'
              - '.github/actions/python-requirements/**'
           
  Friesian-Scala-UT:
    needs: changes
    if: ${{ needs.changes.outputs.friesian == 'true' }}
    runs-on: [ self-hosted, ubuntu-20.04-lts, CLX, AVX512, Ettenmoors ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up maven
        uses: ./.github/actions/maven-setup-action
      - name: Run test
        uses: ./.github/actions/friesian-scala-ut-action

  Dllib-Scala-UT:
    needs: changes
    if: ${{ needs.changes.outputs.dllib == 'true' }}
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up maven
        uses: ./.github/actions/maven-setup-action
      - name: Run test
        uses: ./.github/actions/dllib-scala-ut-action

  PPML-Scala-UT:
    needs: changes
    if: ${{ needs.changes.outputs.ppml == 'true' }}
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK8
        uses: ./.github/actions/jdk-setup-action
      - name: Set up maven
        uses: ./.github/actions/maven-setup-action
      - name: Run test
        uses: ./.github/actions/ppml-scala-ut-action

  Orca-Ray-Ctx-Example:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin-resources, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Run test
      uses: ./.github/actions/orca-ray-ctx-example-action

  Orca-Python-ExampleTest-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-orca-python-py37-spark3
    - name: Run Test
      uses: ./.github/actions/orca/orca-python-exampletest-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Orca-Python-ExampleTest-Ray-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-orca-python-py37-spark3
    - name: Run Test
      uses: ./.github/actions/orca/orca-python-exampletest-ray-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Orca-Python-ExampleTest-Horovod-Pytorch-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action 
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-orca-horovod-pytorch-py37
    - name: Run Test
      uses: ./.github/actions/orca/orca-python-exampletest-horovod-pytorch-py37-spark3-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Orca-Python-ExampleTest-Horovod-Tf-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action 
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-horovod-tf2-py37
    - name: Run Test
      uses: ./.github/actions/orca/orca-python-exampletest-horovod-tf2-py37-spark3-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Orca-Jep-ExampleTest-Py37-Spark2:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-jep-exampletest-py37
    - name: Run Test
      uses: ./.github/actions/orca/orca-jep-exampletest-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env
  
  Orca-Python-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-orca-python-py37-spark3
    - name: Run Test
      uses: ./.github/actions/orca/orca-python-py37-spark3-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env
  
  Orca-Python-Ray-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-orca-python-py37-spark3
    - name: Run Test
      uses: ./.github/actions/orca/orca-python-ray-py37-spark3-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Orca-Python-Horovod-Tf2-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action 
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-horovod-tf2-py37
    - name: Run Test
      uses: ./.github/actions/orca/orca-python-horovod-tf2-py37-spark3-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Orca-Python-Horovod-Pytorch-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action 
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-orca-horovod-pytorch-py37
    - name: Run Test
      uses: ./.github/actions/orca/orca-python-horovod-pytorch-py37-spark3-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Orca-Jep-Python-Py37-Spark2:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-jep-exampletest-py37
    - name: Run Test
      uses: ./.github/actions/orca/orca-jep-python-py37-spark2-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Orca-Python-Rayonspark-Tf2-Py37:
    needs: changes
    if: ${{ needs.changes.outputs.orca == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action 
    - name: Setup env
      uses: ./.github/actions/orca/setup-env/setup-rayonspark-tf2-py37
    - name: Run Test
      uses: ./.github/actions/orca/orca-rayonspark-tf2-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  PPML-Python-UT-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.ppml == 'true' }}
    runs-on: [ self-hosted, Gondolin, ubuntu-20.04-lts ]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/ppml/setup-env/setup-ppml-python-ut-spark3
    - name: Run Test
      uses: ./.github/actions/ppml/ppml-python-ut-spark3-action/pr-test
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env
  
  Friesian-Python-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.friesian == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/friesian/setup-env/setup-friesian-python-py37-spark3
    - name: Run Test
      uses: ./.github/actions/friesian/friesian-python-py37-spark3/
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env
    
  Friesian-Python-Py37-Spark3-Pip:
    needs: changes
    if: ${{ needs.changes.outputs.friesian == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/friesian/setup-env/setup-friesian-python-py37-spark3
    - name: Run Test
      uses: ./.github/actions/friesian/friesian-python-py37-spark3-pip/
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Friesian-Python-ExampleTest-Feature-Tf1-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.friesian == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/friesian/setup-env/setup-friesian-python-py37-spark3
    - name: Run Test
      uses: ./.github/actions/friesian/friesian-python-exampletest-feature-tf1-py37-spark3/
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Friesian-Python-ExampleTest-Feature-Tf1-Pip-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.friesian == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/friesian/setup-env/setup-friesian-python-py37-spark3
    - name: Run Test
      uses: ./.github/actions/friesian/friesian-python-exampletest-feature-tf1-pip-py37-spark3/
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Friesian-Python-ExampleTest-Tf2-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.friesian == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/friesian/setup-env/setup-friesian-python-tf2-py37-spark3
    - name: Run Test
      uses: ./.github/actions/friesian/friesian-python-exampletest-tf2-py37-spark3
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env

  Friesian-Python-ExampleTest-Tf2-Pip-Py37-Spark3:
    needs: changes
    if: ${{ needs.changes.outputs.friesian == 'true' }}
    runs-on: [self-hosted, Gondolin, ubuntu-20.04-lts]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK8
      uses: ./.github/actions/jdk-setup-action
    - name: Set up maven
      uses: ./.github/actions/maven-setup-action
    - name: Setup env
      uses: ./.github/actions/friesian/setup-env/setup-friesian-python-tf2-py37-spark3
    - name: Run Test
      uses: ./.github/actions/friesian/friesian-python-exampletest-tf2-pip-py37-spark3
    - name: Remove Env
      if: ${{ always() }}
      uses: ./.github/actions/remove-env
